name: CI/CD Pipeline

run-name: ${{ github.actor }} is running a workflow

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "ğŸ”¥ The job was triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ’» The job is running on a ${{ runner.os }} server."
      - run: echo "ğŸ” The name of this branch is ${{ github.ref }} on the ${{ github.repository }} repository."

      - name: Install dependencies
        run: npm i

      - name: Run Biome format
        run: npm run format

      - name: Run tests
        run: npm run test

  security:
    if: false
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: Run security audit
        run: npm audit --audit-level high

  build: 
    if: false
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker build
        uses: docker/setup-build-action@v3

      - name: Build and push
        uses: docker/setup-build-action@v5
        with: 
          context: ./docker
          push: false
          tags: frontend-marketplace:latest