name: CI/CD Pipeline

run-name: ${{ github.actor }} is running a workflow

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  frontend-test:
    runs-on: ubuntu-latest

    if: contains(join(github.event.commits.*.modified, ' '), 'frontend-marketplace/') || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - run: echo "ğŸ”¥ The job was triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ’» The job is running on a ${{ runner.os }} server."
      - run: echo "ğŸ” The name of this branch is ${{ github.ref }} on the ${{ github.repository }} repository."

      - name: Setup Node.js in Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend-marketplace/package-lock.json'

      - name: Install Frontend dependencies
        working-directory: frontend-marketplace
        run: npm ci

      - name: Run Biome format
        working-directory: frontend-marketplace
        run: npm run format

      # - name: Run tests
      #   working-directory: frontend-marketplace
      #   run: npm run test

  backend-test:
    runs-on: ubuntu-latest
    if: contains(join(github.event.commits.*.modified, ' '), 'backend/') || github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js in Backend
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      # - name: Run backend tests
      #   working-directory: backend
      #   run: npm test

  deploy: 
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps: 
      - uses: actions/checkout@v4

      - name: Deploy to production 
        run: |
          echo "Frontend and Backend are ready"